### ISSUE TITLE
AutoHook Bug

### ISSUE THREAD

**Issue by SaltFish-X** [gamous/DalamudPluginsCN-Dev#1]
Min. Wait 翻译为最长等待，导致有两个最长等待导致AutoHook插件存在bug

你fork的AutoHook没法提Issues，所以找了个差不多合适的地方提

**Comment by gamous** [comment]
> Min. Wait 翻译为最长等待，导致有两个最长等待导致AutoHook插件存在bug
> 
> 你fork的AutoHook没法提Issues，所以找了个差不多合适的地方提

@SaltFish-X , 感谢提醒，已发布修复，请尝试更新插件，仓库Issue也已打开
