### ISSUE TITLE
请问为什么有些插件显示被禁用

### ISSUE THREAD

**Issue by Crozz333** [gamous/DalamudPluginsCN-Dev#2]
![3B4@TK@D%RI`YP$E533B4XL](https://github.com/gamous/DalamudPluginsCN-Dev/assets/133202759/5341d0ff-c0ba-4365-95cf-14c874ac4896)

**Comment by gamous** [comment]
国服卫月维护团队对部分超出卫月开发者规范的插件就行了禁用，选择SplatoonX作为替代安装或自行寻找其他方式unban

**Comment by Crozz333** [comment]
可以请问一下它的插件库链接吗，我只能找到普通splatoon的（挠头
